config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :jobs, only: [:index, :show, :new, :create]

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user

  include PgSearch::Model
  pg_search_scope :search_by_requirements,
    against: [ :requirements ],
    using: {
      tsearch: { prefix: true }
    }

  REQUIREMENTS = ["HTML", "CSS/SCSS/SASS", "JavaScript", "React JS", "React Native", "Redux", "Angular", "Vue.js", "Bootstrap", "jQuery"]
  FORMAT = ["Estágio", "CLT", "PJ", "Freelance"]
  MODALITY = ["Presencial", "Remoto"]
  LEVEL = ["Junior", "Pleno", "Senior"]

  validates :title, presence: true, length: {maximum: 50}
  validates :location, :description, presence: true
  validates :requirements, presence: :true, length: { minimum: 5}
  validates :format, presence: true, inclusion: { in: FORMAT }
  validates :modality, presence: true, inclusion: { in: MODALITY }
  validates :level, presence: true, inclusion: { in: LEVEL }

  validate :correct_requirements_types

  private

  def correct_requirements_types
    if self.requirements.blank?
      errors.add(:requirements, "is blank/invalid")
    elsif self.requirements.detect { |s| !(REQUIREMENTS.include? s) }
      errors.add(:requirements, "is invalid")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :photo

  has_many :jobs, dependent: :destroy

  validates :company_name, :description, :website, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:company_name, :description, :website])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:company_name, :description, :website])
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      @jobs = Job.search_by_requirements(params[:query])
    else
      @jobs = Job.all
    end
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end
  
  def create
    @job = Job.new(job_params)
    @job.user = current_user

    if @job.save
      redirect_to jobs_path
    else
      render 'new'
    end
  end
  
  private

  def job_params
    return params.require(:job).permit(:title, :location, :description, :format, :modality, :level, :photo, requirements: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/jobs/index.html.erb
<div id='background'>
  <div class='barra' id='topo'>
    <button class='buttonEditar'>
      <%= link_to root_path do %>
        <%= image_tag('arrow-left.png', id: "arrow") %>
        <%= "Editar habilidades" %>
      <% end %>
    </button>

    <%= link_to "Pronta!", root_path, class:"brand" %>
  </div>

  <div class='barra'>
    <p>Você está pronta para se candidatar às vagas abaixo:</p>
  </div>


  <!-- Cards são inseridos dentro da div abaixo com ID Container -->
  <div id='container'>
    <% @jobs.each do |job| %>
      <div id='box'>
        <div class="card">
          <div class="topo">
            <%= cl_image_tag job.user.photo.key, crop: :fit, width: 200, height: 400 %>
            <div class='titulo'>
              <p class='titulovaga'><%= job.title %></p>
              <p><%= job.user.company_name %></p>
            </div>
          </div>

          <p class='descricao'><%= job.description %></p>
          
          <div class='caracteristicas'>
              <div class='caracteristica'><%= job.level %></div>
              <div class='caracteristica'><%= job.format %></div>
              <div class='caracteristica'><%= job.modality %></div>
          </div>

          <div class='buttons'>
            <button class='buttondetalhes'>
              <%= link_to job_path(job.id) do %>
                <%= "Mais detalhes" %>
              <% end %>
            </button>

            <button class='buttoncandidatar'>
              <%= mail_to job.user.email do %>
                <%= "Me candidatar" %>
              <% end %>
            </button>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/jobs/new.html.erb
<h2><%= "Adicionar nova vaga" %></h2>

<%= simple_form_for(@job) do |f| %>
  <%= f.input :title %>
  <%= f.input :location %>
  <%= f.input :description %>
  <%= f.input :requirements, include_hidden: false, collection: Job::REQUIREMENTS, as: :check_boxes %>
  <%= f.input :format, collection: Job::FORMAT %>
  <%= f.input :modality, collection: Job::MODALITY %>
  <%= f.input :level, collection: Job::LEVEL %>
  <%= f.button :submit, "Publicar vaga" %>
<% end %>

<%= link_to "Voltar", jobs_path %>

app/views/jobs/show.html.erb
<div id='background-show'>
  <div class='barra' id='topo'>
    <button class='buttonEditar'>
      <%= link_to jobs_path do %>
        <%= image_tag('arrow-left.png', id: "arrow") %>
        <%= "Ver todas as vagas" %>
      <% end %>
    </button>

    <%= link_to "Pronta!", root_path, class:"brand" %>
  </div>

  <div id='detalhes-show'>
    <div class='topo-show'>
      <%= cl_image_tag @job.user.photo.key, crop: :fit, width: 200, height: 400, class: "show" %>
      <div class='titulodiv-show'>
        <p class='titulovaga-show'><%= @job.title %></p>
        <p class='nomeempresa-show'><%= @job.user.company_name %> - <%= @job.location %></p>
      </div>
    </div>

    <div class='habilidades-show'>
      <div class='habilidade-show'><%= @job.level %></div>
      <div class='habilidade-show'><%= @job.format %></div>
      <div class='habilidade-show'><%= @job.modality %></div>
    </div>

    <p id='titulodescricao-show'>Venha fazer parte do nosso time!</p>

    <div id='descricaovaga-show'>
      <p id='titulodescricao-show'>Sobre a <%= @job.user.company_name %></p>
      <p class="pb-3 mb-3 pr-4"><%= @job.user.description %></p>
      
      <p id='titulodescricao-show'>Sobre a vaga de <%= @job.title %></p>
      <p class="pb-3 mb-3 pr-4"><%= @job.description %></p>

      <p id='titulodescricao-show'>Requisitos<p>
      <ul class="pl-3 ml-1">
        <% @job.requirements.each do |requirement| %>
          <li class="show"><%= requirement %></li>
        <% end %>
      </ul>
    </div>

    <div class="mb-5 ml-5">
      <button id='mecandidatar-show'>
        <%= mail_to @job.user.email do %>
          <%= "Me candidatar" %>
        <% end %>
      </button>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pronta! | Conheça o seu verdadeiro potencial profissional</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="pronta-wrapper">
  <div class="logo">
    <div>
      <div class="principal">
        <h1>Pronta!</h1>
      </div>

      <div class="mensagem">
        <h2>Match de habilidades</h2>
        <h3>Conheça o seu verdadeiro <br> potencial profissional.</h3>
      </div>
    </div>
  </div>

  <div class="busca">
    <div class="caixa-busca">
      <div class="texto-busca mb-5">
        <h4>Quais são suas principais habilidades?</h4>
        <p>Selecione ao menos 5 para melhores resultados</p>
      </div>

      <form action="/jobs?query=">
        <fieldset class="pl-3 pb-4">
          <label>
            <input type="checkbox" name="query" id="ling01" value="html">
            <span><label for="ling01" class="pt-2">HTML</label></span>
          </label>
          
          <label>
            <input type="checkbox" name="query" id="ling02" value="css/scss/sass">
            <span><label for="ling02" class="pt-2">CSS/SCSS/SASS</label></span>
          </label>

          <label>
            <input type="checkbox" name="query" id="ling03" value="javascript">
            <span><label for="ling03" class="pt-2">JavaScript</label></span>
          </label>

          <label>
            <input type="checkbox" name="query" id="ling04" value="react js">
            <span><label for="ling04" class="pt-2">React JS</label></span>
          </label>

          <label>
            <input type="checkbox" name="query" id="ling05" value="react native">
            <span><label for="ling05" class="pt-2">React Native</label></span>
          </label>

          <label>
            <input type="checkbox" name="query" id="ling06" value="redux">
            <span><label for="ling06" class="pt-2">Redux</label></span>
          </label>

          <br>

          <label>
            <input type="checkbox" name="query" id="ling07" value="angular">
            <span><label for="ling07" class="pt-2">Angular</label></span>
          </label>         
                
          <label>
            <input type="checkbox" name="query" id="ling08" value="vue.js">
            <span><label for="ling08" class="pt-2">Vue.js</label></span>
          </label>

          <label>
            <input type="checkbox" name="query" id="ling09" value="bootstrap">
            <span><label for="ling09" class="pt-2">Bootstrap</label></span>
          </label>       

          <label>
            <input type="checkbox" name="query" id="ling10" value="jquery">
            <span><label for="ling10" class="pt-2">jQuery</label></span>
          </label>
        </fieldset>

        <div class="botao pt-5">
          <input type="submit" value="Buscar vagas" id="botao">
        </div>
      </form>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<!-- <% if user_signed_in? %>
    <%= link_to "Home", root_path %>
    <%= link_to "Editar empresa", edit_user_registration_path %>
    <%= link_to "Sair", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Home", root_path %>
  <%= link_to "Acessar como empresa", new_user_session_path %>
<% end %> -->